server:
  port: 8521

spring:
  application:
    name: debriServer

#DB Config
  datasource:
    url: jdbc:mysql://debri-db.ckypat83jyyc.ap-northeast-2.rds.amazonaws.com:3306/Debri_D
    username: admin
    password: debri0626
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

#Logger
logging:
  file:
    name: ${user.dir}/log/test.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
