server:
  port: 8521

spring:
  application:
    name: debriServer
  main:
      allow-circular-references: true

#DB Config
  datasource:
    url: jdbc:mysql://debri-db.ckypat83jyyc.ap-northeast-2.rds.amazonaws.com:3306/Debri_DB
    username: admin
    password: debri0626
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver


#Logger
logging:

  file:
    name: ${user.dir}/log/test.log
  logback:
    rollingpolicy:
      max-history: 7
<<<<<<< HEAD
      max-file-size: 10MB
=======
      max-file-size: 10MB

>>>>>>> 89b4b6d6f56ae977ae3b1d13ca3e5e730b1aa74a
