server:
  port: 8521

spring:
  application:
    name: debriServer
  main:
      allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: debridevelopmentteam@gmail.com
    password: adgovgzslpliasvf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

#DB Config
  datasource:
    url: jdbc:mysql://debri-db.ckypat83jyyc.ap-northeast-2.rds.amazonaws.com:3306/Debri_DB
    username: admin
    password: debri0626
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver


#Logger
logging:

  file:
    name: ${user.dir}/log/test.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
